spring:
  application:
    name: eureka-server
server:
  port: 8071

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false
    register-with-eureka: false